TAG_ALIAS = {
    # NetSales　売上高
    "NetSalesSummaryOfBusinessResults": "NetSales",
    "NetSales": "NetSales",
    "RevenuesFromExternalCustomers": "NetSales",
    "OperatingRevenuesIFRSKeyFinancialData": "NetSales",
    "RevenueIFRS": "NetSales",
    "NetSalesIFRS": "NetSales",
    "Revenue": "NetSales",
    "RevenueFromContractsWithCustomersIFRS": "NetSales",
    "OperatingRevenue": "NetSales",
    "OperatingRevenue1": "NetSales",
    "OperatingRevenue1SummaryOfBusinessResults": "NetSales",
    "OperatingRevenueIFRS": "NetSales",
    "OperatingRevenues": "NetSales",
    "RevenueIFRSSummaryOfBusinessResults": "NetSales",
    "Revenue2IFRS": "NetSales",
    "RevenueFromExternalCustomers2IFRS": "NetSales",
    "RevenueFromContractsWithCustomers": "NetSales",
    "NetSalesOfCompletedConstructionContractsCNS": "NetSales",
    "NetSalesOfCompletedConstructionContractsSummaryOfBusinessResults": "NetSales",
    "OperatingRevenuesSummaryOfBusinessResults": "NetSales",
    "TotalBusinessRevenueRevOA": "NetSales",
    "BusinessRevenue": "NetSales",
    "BusinessRevenueSummaryOfBusinessResults": "NetSales",
    "BusinessRevenueRevOA": "NetSales",
    "BusinessRevenueKeyFinancialData": "NetSales",
    "BusinessRevenues": "NetSales",
    "OperatingRevenueSummaryOfBusinessResults": "NetSales",
    "OperatingRevenuesRevOA": "NetSales",
    "OperatingRevenueRevOA": "NetSales",
    "NetSalesOfGoodsRevOA": "NetSales",
    "NetSalesOfFinishedGoodsRevOA": "NetSales",
    "RevenuesUSGAAPSummaryOfBusinessResults": "NetSales",
    "OrdinaryIncomeBNK": "NetSales",
    "OrdinaryIncomeSummaryOfBusinessResults": "NetSales",
    "InsurancePremiumsAndOtherOIINS": "NetSales",
    "InsurancePremiumsAndOtherSummaryOfBusinessResults": "NetSales",
    "InsurancePremiumsAndOthersSummaryOfBusinessResults": "NetSales",
    "PremiumAndOtherIncomeSummaryOfBusinessResults": "NetSales",
    "InsuranceRevenueIFRS": "NetSales",
    "InsuranceRevenueIFRSKeyFinancialData": "NetSales",
    "InsuranceClaimsAndOthersSummaryOfBusinessResults": "InsuranceClaimsPayments",
    "ProvisionOfPolicyReserveAndOtherOEINS": "PolicyReserveProvision",
    "InvestmentExpensesOEINS": "InvestmentExpenses",
    "ProjectExpensesINS": "ProjectExpenses",
    "NetRevenueSummaryOfBusinessResults": "GrossProfit",
    "InterestIncomeOIBNK": "FundingIncome",
    "FeesAndCommissionsOIBNK": "FeesAndCommissionsIncome",

    # CostOfSales　売上原価
    "CostOfSales": "CostOfSales",
    "CostOfSalesIFRS": "CostOfSales",
    "CostOfRevenue": "CostOfSales",
    "CostOfRevenueIFRS": "CostOfSales",
    "CostOfOperatingRevenue": "CostOfSales",
    "CostOfOperatingRevenueIFRS": "CostOfSales",
    "OperatingCosts": "CostOfSales",
    "OperatingCostsIFRS": "CostOfSales",
    "OperatingCost": "CostOfSales",
    "OperatingCost2": "CostOfSales",
    "CostOfRevenueFromContractsWithCustomersIFRS": "CostOfSales",
    "CostOfGoodsSold": "CostOfSales",
    "CostOfGoodsSoldIFRS": "CostOfSales",
    "CostOfSalesOfCompletedConstructionContractsCNS": "CostOfSales",
    "CostOfSalesOfCompletedConstructionContractsSummaryOfBusinessResults": "CostOfSales",
    "OperatingExpensesAndCostOfSalesOfTransportationRWY": "CostOfSales",
    "TotalBusinessExpensesCOSExpOA": "CostOfSales",
    "CostOfBusinessRevenue": "CostOfSales",
    "CostOfBusinessRevenueBusinessExpenses": "CostOfSales",
    "CostOfBusinessRevenueCOSExpOA": "CostOfSales",
    "CostOfRawMaterialsCOS": "CostOfSales",
    "CostOfCompletedWorkCOSExpOA": "CostOfSales",
    "CostOfFinishedGoodsSold": "CostOfSales",
    "GoodsConsignmentMerchandiseCostOfFinishedGoodsSoldCOS": "CostOfSales",
    "FinancingExpensesOpeCFBNK": "CostOfSales",
    "FinancialExpensesSEC": "CostOfSales",
    "CostOfSalesAndSellingGeneralAndAdministrativeExpensesIFRS": "CostOfSalesAndSellingGeneralAndAdministrativeExpenses",
    "ExpenseIFRS": "CostOfSalesAndSellingGeneralAndAdministrativeExpenses",
    "OperatingExpensesIFRS": "CostOfSalesAndSellingGeneralAndAdministrativeExpenses",
    "OperatingExpenses": "CostOfSalesAndSellingGeneralAndAdministrativeExpenses",
    "OperatingExpensesOILTelecommunications": "CostOfSalesAndSellingGeneralAndAdministrativeExpenses",
    "ElectricUtilityOperatingExpensesELE": "CostOfSalesAndSellingGeneralAndAdministrativeExpenses",
    "ElectricUtilityOperatingExpenses": "CostOfSalesAndSellingGeneralAndAdministrativeExpenses",
    "BusinessExpenses": "CostOfSalesAndSellingGeneralAndAdministrativeExpenses",
    "OperatingExpensesOE": "CostOfSalesAndSellingGeneralAndAdministrativeExpenses",
    "OperatingExpensesINS": "CostOfSalesAndSellingGeneralAndAdministrativeExpenses",
    "OperatingCostsAndExpensesCOSExpOA": "CostOfSalesAndSellingGeneralAndAdministrativeExpenses",
    "OrdinaryExpensesBNK": "CostOfSalesAndSellingGeneralAndAdministrativeExpenses",

    # GrossProfit　売上総利益
    "GrossProfit": "GrossProfit",
    "GrossProfitIFRS": "GrossProfit",
    "GrossProfitSummaryOfBusinessResults": "GrossProfit",
    "GrossProfitIFRSSummaryOfBusinessResults": "GrossProfit",
    "GrossProfitOnCompletedConstructionContractsCNS": "GrossProfit",
    "GrossProfitOnCompletedConstructionContractsSummaryOfBusinessResults": "GrossProfit",
    "BusinessGrossProfitOrLoss": "GrossProfit",
    "OperatingGrossProfit": "GrossProfit",
    "OperatingGrossProfitIFRS": "GrossProfit",
    "OperatingGrossProfitWAT": "GrossProfit",
    "OperatingGrossProfitNetGP": "GrossProfit",

    # SellingExpenses　販管費
    "SellingGeneralAndAdministrativeExpenses": "SellingExpenses",
    "SellingGeneralAndAdministrativeExpensesIFRS": "SellingExpenses",
    "SellingExpensesAndGeneralAdministrativeExpenses": "SellingExpenses",
    "SellingExpensesAndGeneralAdministrativeExpensesIFRS": "SellingExpenses",
    "AdministrativeExpenses": "SellingExpenses",
    "AdministrativeExpensesIFRS": "SellingExpenses",
    "DistributionCosts": "SellingExpenses",
    "DistributionCostsIFRS": "SellingExpenses",
    "SalesAndMarketingExpenses": "SellingExpenses",
    "SalesAndMarketingExpensesIFRS": "SellingExpenses",
    "GeneralAndAdministrativeExpensesIFRS": "SellingExpenses",
    "GeneralAndAdministrativeExpensesSGA": "SellingExpenses",
    "SellingGeneralAndAdministrativeExpense": "SellingExpenses",
    "GeneralAndAdministrativeExpenses": "SellingExpenses",
    "SellingGeneralAdministrativeExpenses": "SellingExpenses",
    "GeneralAndAdministrativeExpensesOEBNK": "SellingExpenses",

    # OperatingIncome　営業利益
    "OperatingIncome": "OperatingIncome",
    "OperatingProfitLossIFRS": "OperatingIncome",
    "OperatingProfit": "OperatingIncome",
    "OperatingProfitIFRS": "OperatingIncome",
    "OperatingLossIFRS": "OperatingIncome",
    "OperatingIncomeIFRS": "OperatingIncome",
    "OperatingIncomeIFRSSummaryOfBusinessResults": "OperatingIncome",
    "OperatingIncomeLoss": "OperatingIncome",
    "OperatingIncomeLossIFRS": "OperatingIncome",
    "OperatingProfitLoss": "OperatingIncome",
    "OperatingIncomeLossSummaryOfBusinessResults": "OperatingIncome",

    # OrdinaryIncome　経常利益
    "OrdinaryIncomeLossSummaryOfBusinessResults": "OrdinaryIncome",
    "OrdinaryIncome": "OrdinaryIncome",
    "ProfitLossBeforeTaxIFRSSummaryOfBusinessResults": "OrdinaryIncome",
    "ProfitBeforeIncomeTaxesFromContinuingIFRSKeyFinancialData": "OrdinaryIncome",
    "ProfitBeforeTax": "OrdinaryIncome",
    "ProfitBeforeTaxIFRS": "OrdinaryIncome",
    "ProfitLossBeforeTax": "OrdinaryIncome",
    "ProfitLossBeforeTaxIFRS": "OrdinaryIncome",
    "ProfitLossBeforeIncomeTaxes": "OrdinaryIncome",
    "ProfitLossBeforeIncomeTaxesIFRS": "OrdinaryIncome",
    "IncomeBeforeIncomeTaxes": "OrdinaryIncome",
    "IncomeBeforeIncomeTaxesIFRS": "OrdinaryIncome",
    "ProfitBeforeIncomeTaxes": "OrdinaryIncome",
    "ProfitBeforeIncomeTaxesIFRS": "OrdinaryIncome",
    "ProfitBeforeTaxFromContinuingOperationsIFRS": "OrdinaryIncome",
    "ProfitBeforeTaxFromContinuingOperations": "OrdinaryIncome",

    # ProfitLoss　純利益
    "ProfitLossAttributableToOwnersOfParentSummaryOfBusinessResults": "ProfitLoss",
    "ProfitLossAttributableToOwnersOfParent": "ProfitLoss",
    "ProfitLoss": "ProfitLoss",
    "ProfitLossAttributableToOwnersOfParentIFRS": "ProfitLoss",
    "ProfitLossIFRS": "ProfitLoss",
    "ProfitLossAttributableToOwnersOfParentSummaryOfBusinessResultsIFRS": "ProfitLoss",
    "ProfitLossIFRSSummaryOfBusinessResults": "ProfitLoss",
    "ProfitLossAttributableToOwnersOfParentIFRSSummaryOfBusinessResults": "ProfitLoss",


    # 営業CF
    "NetCashProvidedByUsedInOperatingActivitiesSummaryOfBusinessResults": "OperatingCash",
    "NetCashProvidedByUsedInOperatingActivities": "OperatingCash",
    "NetCashProvidedByUsedInOperatingActivitiesIFRS": "OperatingCash",
    "CashFlowsFromUsedInOperatingActivitiesIFRSSummaryOfBusinessResults": "OperatingCash",
    "CashFlowsFromUsedInOperatingActivitiesUSGAAPSummaryOfBusinessResults": "OperatingCash",

    # 投資CF
    "NetCashProvidedByUsedInInvestingActivitiesSummaryOfBusinessResults": "InvestmentCash",
    "NetCashProvidedByUsedInInvestmentActivities": "InvestmentCash",
    "NetCashProvidedByUsedInInvestingActivities": "InvestmentCash",
    "NetCashProvidedByUsedInInvestingActivitiesIFRS": "InvestmentCash",
    "CashFlowsFromUsedInInvestingActivitiesIFRSSummaryOfBusinessResults": "InvestmentCash",
    "CashFlowsFromUsedInInvestingActivitiesUSGAAPSummaryOfBusinessResults": "InvestmentCash",

    # 財務CF
    "NetCashProvidedByUsedInFinancingActivitiesSummaryOfBusinessResults": "FinancingCash",
    "NetCashProvidedByUsedInFinancingActivities": "FinancingCash",
    "NetCashProvidedByUsedInFinancingActivitiesIFRS": "FinancingCash",
    "CashFlowsFromUsedInFinancingActivitiesIFRSSummaryOfBusinessResults": "FinancingCash",
    "CashFlowsFromUsedInFinancingActivitiesUSGAAPSummaryOfBusinessResults": "FinancingCash",

    # 資産
    "TotalAssetsSummaryOfBusinessResults": "TotalAssets",
    "TotalAssetsIFRSSummaryOfBusinessResults": "TotalAssets",
    "AssetsIFRS": "TotalAssets",
    "TotalAssets": "TotalAssets",
    "TotalAssetsIFRS": "TotalAssets",

    # 資本
    "NetAssets": "NetAssets",
    "NetAssetsSummaryOfBusinessResults": "NetAssets",
    "EquityAttributableToOwnersOfParentIFRSSummaryOfBusinessResults": "NetAssets",
    "EquityAttributableToOwnersOfParentIFRS": "NetAssets",
    "EquityIFRS": "NetAssets",

    # 期末残
    "CashAndCashEquivalents": "CashAndCashEquivalents",
    "CashAndCashEquivalentsSummaryOfBusinessResults": "CashAndCashEquivalents",
    "CashAndCashEquivalentsIFRSSummaryOfBusinessResults": "CashAndCashEquivalents",
    "CashAndCashEquivalentsIFRS": "CashAndCashEquivalents",
    "CashAndCashEquivalentsUSGAAPSummaryOfBusinessResults": "CashAndCashEquivalents",

    # 発行株数
    "NumberOfIssuedSharesAsOfFiscalYearEndIssuedSharesTotalNumberOfSharesEtc": "IssuedShares",
    "NumberOfIssuedSharesAsOfFilingDateIssuedSharesTotalNumberOfSharesEtc": "IssuedShares",
    "TotalNumberOfIssuedSharesIssuedSharesTotalNumberOfSharesEtc": "IssuedShares",
    "TotalNumberOfIssuedSharesSummaryOfBusinessResults": "IssuedShares",
    "TotalNumberOfIssuedSharesCommonStockIssuedSharesTotalNumberOfSharesEtc": "IssuedShares",
    "TotalNumberOfIssuedSharesOrdinaryShareIssuedSharesTotalNumberOfSharesEtc": "IssuedShares",

    # 自己株式
    "TotalNumberOfSharesHeldTreasurySharesEtc": "TreasuryShares",
    "NumberOfSharesHeldInOwnNameTreasurySharesEtc": "TreasuryShares",
    "TotalNumberOfSharesHeldInTheNameOfOthersTreasurySharesEtc": "TreasuryShares",
    "TotalNumberOfSharesHeldInOwnNameTreasurySharesEtc": "TreasuryShares",
    "TotalNumberOfTreasurySharesSummaryOfBusinessResults": "TreasuryShares",
    "NumberOfTreasurySharesAsOfFiscalYearEndIssuedSharesTotalNumberOfSharesEtc": "TreasuryShares",
    "TreasurySharesAtTheEndOfFiscalYearIssuedSharesTotalNumberOfSharesEtc": "TreasuryShares",
}


def normalize_tag_to_metric(tag: str) -> str | None:
    return TAG_ALIAS.get(tag)


def allowed_raw_fact_tags() -> set[str]:
    return set(TAG_ALIAS.keys())
